name: Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: docker.io
      tags: latest